x-common-env: &common-env
  TZ: ${TZ:?Timezone not set}

  MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD not set}
  MYSQL_DATABASE: ${MYSQL_DATABASE:?MYSQL_DATABASE not set}
  MYSQL_USER: ${MYSQL_USER:?MYSQL_USER not set}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD not set}

  USER_USERNAME: ${USER_USERNAME:?USER_USERNAME not set}
  USER_PASSWORD: ${USER_PASSWORD:?USER_PASSWORD not set}
  ADMIN_USERNAME: ${ADMIN_USERNAME:?ADMIN_USERNAME not set}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD:?ADMIN_PASSWORD not set}

  SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE:?MYSQL_DATABASE not set}
  SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:?MYSQL_USER not set}
  SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:?MYSQL_PASSWORD not set}

services:
  db:
    image: mysql:8.0
    environment:
      <<: *common-env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysql", "-u", "${MYSQL_USER:?MYSQL_USER not set}", "-p${MYSQL_PASSWORD:?MYSQL_PASSWORD not set}", "-e", "SELECT 1" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s  # Give 30s before checking container health

  builder:
    image: eclipse-temurin:17-jdk-alpine
    working_dir: /library-app
    volumes:
      - .:/library-app
      - ./docs:/library-app/target/reports/apidocs
      - maven-cache:/root/.m2/repository
      - build-artifacts:/library-app/target
    depends_on:
      db:
        condition: service_healthy
    environment:
      <<: *common-env
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    command: >
      sh -c "
        ./mvnw dependency:go-offline --batch-mode &&
        ./mvnw package $([ \"${RUN_TESTS:-true}\" = \"false\" ] && echo \"-DskipTests\") --batch-mode javadoc:javadoc
        exit $?
      "

  app:
    image: eclipse-temurin:17-jre-alpine
    working_dir: /library-app
    volumes:
      - build-artifacts:/library-app/target
    ports:
      - "8080:8080"
    depends_on:
      builder:
        condition: service_completed_successfully
      db:
        condition: service_healthy
    environment:
      <<: *common-env
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: >
      sh -c "java -jar /library-app/target/library-management-system-0.0.1-SNAPSHOT.jar"

volumes:
  maven-cache:
  build-artifacts:
